# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('xing', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('figure', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=50)),
            ],
            managers=[
                ('apple_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
